import {
  Activity,
  ArrowLeftRight,
  ChartColumn,
  BarChart3,
  BrainCircuit,
  CandlestickChart,
  Coins,
  Database,
  SearchCode,
  ImageIcon,
  Landmark,
  LayoutDashboard,
  Shield,
  Send,
  Settings2,
  SlidersHorizontal,
  TerminalSquare,
  TriangleAlert,
  Users,
  Vote,
  WalletCards,
  Wallet,
} from "lucide-react";

export const NAV_ITEMS = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    id: "wallet",
    label: "Wallet",
    href: "/dashboard/wallet",
    icon: Wallet,
  },
  {
    id: "markets",
    label: "Markets",
    href: "/dashboard/markets",
    icon: BarChart3,
  },
  {
    id: "trading",
    label: "Trading",
    href: "/dashboard/trading",
    icon: CandlestickChart,
  },
  {
    id: "transfer",
    label: "Transfer",
    href: "/dashboard/transfer",
    icon: Send,
  },
  {
    id: "stake",
    label: "Stake",
    href: "/dashboard/stake",
    icon: WalletCards,
  },
  {
    id: "pools",
    label: "Pools",
    href: "/dashboard/pools",
    icon: Database,
  },
  {
    id: "borrow",
    label: "Borrow",
    href: "/dashboard/borrow",
    icon: Landmark,
  },
  {
    id: "governance",
    label: "Governance",
    href: "/dashboard/governance",
    icon: Vote,
  },
  {
    id: "treasury",
    label: "Treasury",
    href: "/dashboard/treasury",
    icon: Landmark,
  },
  {
    id: "tokens",
    label: "Tokens",
    href: "/dashboard/tokens",
    icon: Coins,
  },
  {
    id: "nfts",
    label: "NFTs",
    href: "/dashboard/nfts",
    icon: ImageIcon,
  },
  {
    id: "swap",
    label: "Swap",
    href: "/dashboard/swap",
    icon: ArrowLeftRight,
  },
  {
    id: "analytics",
    label: "Analytics",
    href: "/dashboard/analytics",
    icon: ChartColumn,
  },
  {
    id: "assistant",
    label: "Assistant",
    href: "/dashboard/assistant",
    icon: BrainCircuit,
  },
  {
    id: "strategy",
    label: "Strategy",
    href: "/dashboard/strategy",
    icon: SlidersHorizontal,
  },
  {
    id: "risk",
    label: "Risk",
    href: "/dashboard/risk",
    icon: TriangleAlert,
  },
  {
    id: "social",
    label: "Social",
    href: "/dashboard/social",
    icon: Users,
  },
  {
    id: "security",
    label: "Security",
    href: "/dashboard/security",
    icon: Shield,
  },
  {
    id: "network",
    label: "Network",
    href: "/dashboard/network",
    icon: Activity,
  },
  {
    id: "settings",
    label: "Settings",
    href: "/dashboard/settings",
    icon: Settings2,
  },
  {
    id: "explorer",
    label: "Explorer",
    href: "/dashboard/explorer",
    icon: SearchCode,
  },
  {
    id: "devtools",
    label: "DevTools",
    href: "/dashboard/devtools",
    icon: TerminalSquare,
  },
  {
    id: "portfolio",
    label: "Portfolio",
    href: "/dashboard/portfolio",
    icon: WalletCards,
  },
  {
    id: "admin",
    label: "Admin",
    href: "/dashboard/admin",
    icon: Settings2,
  },
];

export const TOKEN_OPTIONS = [
  { label: "SOL", value: "SOL", name: "Solana", color: "from-cyan-300 to-blue-500" },
  { label: "USDC", value: "USDC", name: "USD Coin", color: "from-blue-400 to-cyan-500" },
  { label: "STRK", value: "STRK", name: "Starknet", color: "from-sky-300 to-cyan-400" },
  { label: "RAY", value: "RAY", name: "Raydium", color: "from-cyan-400 to-indigo-500" },
  { label: "BTC", value: "BTC", name: "Bitcoin", color: "from-cyan-300 to-emerald-400" },
  { label: "ETH", value: "ETH", name: "Ethereum", color: "from-blue-300 to-violet-400" },
  { label: "GOV", value: "GOV", name: "Governance Token", color: "from-cyan-300 to-blue-500" },
  { label: "RTX", value: "RTX", name: "Retix Token", color: "from-cyan-300 to-blue-500" },
  { label: "BONK", value: "BONK", name: "Bonk", color: "from-orange-300 to-amber-500" },
  { label: "MSOL", value: "MSOL", name: "Marinade Staked SOL", color: "from-emerald-300 to-cyan-500" },
];

export const STATUS_TONES: Record<string, string> = {
  active: "border-[rgba(224,185,75,0.2)] bg-[rgba(224,185,75,0.1)] text-[#f3d57c]",
  completed: "border-emerald-400/20 bg-emerald-500/12 text-emerald-300",
  claimed: "border-emerald-400/20 bg-emerald-500/12 text-emerald-300",
  pending: "border-amber-400/20 bg-amber-500/12 text-amber-300",
  paused: "border-amber-400/20 bg-amber-500/12 text-amber-300",
  failed: "border-rose-400/20 bg-rose-500/12 text-rose-300",
  rejected: "border-rose-400/20 bg-rose-500/12 text-rose-300",
  passed: "border-emerald-400/20 bg-emerald-500/12 text-emerald-300",
};
